# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'devopshusiana'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      # Clone Azure-hpc
      git clone https://github.com/Azure/azurehpc.git
      # retrieve rsa-keys from KeyVault
      echo Fetching rsapub
      az keyvault secret download --name idrsadevopspub --vault-name devopsvaulthusiana -f hpcadmin_id_rsa.pub
      echo Fetching rsapriv
      az keyvault secret download --name idrsadevops --vault-name devopsvaulthusiana -f hpcadmin_id_rsa
      # Install the SLURM-Cluster
      echo Run the first script
      /bin/bash ./scripts/0-azhpc-slurm.sh

# TO THE END - deleting everything.
#- task: AzureCLI@2
#  inputs:
#    azureSubscription: 'devopshusiana'
#    scriptType: 'bash'
#    scriptLocation: 'inlineScript'
#    inlineScript: |
#      /bin/bash ./scripts/10-delete-rg.sh
