# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'devopshusiana'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      # Clone Azure-hpc
      git clone https://github.com/Azure/azurehpc.git
      # retrieve rsa-keys from KeyVault
      az keyvault secret download --name idrsadevopspub --vault-name devopsvaulthusiana -f hpcadmin_id_rsa.pub
      az keyvault secret download --name idrsadevops --vault-name devhopsvaulthusiana -f hpcadmin_id_rsa
      # Install the SLURM-Cluster
      /bin/bash ./scripts/0-azhpc-slurm.sh

#- script: |
#    echo Add other tasks to build, test, and deploy your project.
#    echo See https://aka.ms/yaml
#  displayName: 'Run a multi-line script'
